/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinalCuestionario;
import java.awt.Color;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.*;
/**
 *
 * @author Miriam
 */
public class TestForm extends javax.swing.JFrame {
    ArrayList<Pregunta> preguntas;
    JRadioButton radios[]=new JRadioButton[3];
    static int  puntaje;
    String villano="";
    int numeroPregunta=0;
    int tiempo=60; 
    /**
     * Creates new form TestForm
     */
    public TestForm() {
       
      
        preguntas=Arreglo.obtenerPregunta();
        initComponents();
         PonerPreguntas(); 
        
        Thread t1=new Thread(new Runnable(){
            @Override
            
            public void run(){
                while(true){
                tiempo --;
                etiquetaReloj.setText("" +tiempo);
                
                
                if(tiempo<10 ){
               etiquetaReloj.setForeground(Color.red);
                etiquetaReloj.setText("" +tiempo);
                    if(tiempo<=0){
         
                        dispose();
                    }
                }
                
                    
                
                  try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
            
                 }
                
            }
            
        });
       
        t1.start();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Radio0 = new javax.swing.JRadioButton();
        Radio1 = new javax.swing.JRadioButton();
        Radio2 = new javax.swing.JRadioButton();
        Siguiente = new javax.swing.JButton();
        EtiquetaPregunta = new javax.swing.JLabel();
        etiquetaReloj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¿Que villano eres?");

        buttonGroup1.add(Radio0);
        Radio0.setText("jRadioButton1");
        Radio0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Radio0.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        buttonGroup1.add(Radio1);
        Radio1.setText("jRadioButton2");
        Radio1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Radio1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        buttonGroup1.add(Radio2);
        Radio2.setText("jRadioButton3");
        Radio2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Radio2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Siguiente.setText("Sigue");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        EtiquetaPregunta.setText("jLabel2");

        etiquetaReloj.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Radio1)
                                .addComponent(Radio0)
                                .addComponent(Radio2))
                            .addComponent(EtiquetaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Siguiente)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaReloj)
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(etiquetaReloj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Radio0)
                .addGap(13, 13, 13)
                .addComponent(Radio1)
                .addGap(18, 18, 18)
                .addComponent(Radio2)
                .addGap(33, 33, 33)
                .addComponent(Siguiente)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        numeroPregunta ++;
        PonerPreguntas();
      // puntaje=Arreglo.obtenerPregunta();}
    }//GEN-LAST:event_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaPregunta;
    private javax.swing.JRadioButton Radio0;
    private javax.swing.JRadioButton Radio1;
    private javax.swing.JRadioButton Radio2;
    private javax.swing.JButton Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etiquetaReloj;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

public void PonerPreguntas(){
    
if(numeroPregunta<preguntas.size()){
    radios[0]=Radio0;
    radios[1]=Radio1;
    radios[2]=Radio2;

ArrayList<Pregunta> preguntas= Arreglo.obtenerPregunta();
        EtiquetaPregunta.setText(preguntas.get(numeroPregunta).getPregunta());
        
            Radio0.setText(preguntas.get(numeroPregunta).getOpciones().get(0).getOpc());
            Radio1.setText(preguntas.get(numeroPregunta).getOpciones().get(1).getOpc());
            Radio2.setText(preguntas.get(numeroPregunta).getOpciones().get(2).getOpc());

            for(int i=0;i<3;i++){
            if(radios[i].isSelected()){
                puntaje=puntaje + preguntas.get(numeroPregunta).getOpciones().get(i).getPuntos();
               
                System.out.println(puntaje);
            }
        }
      }

   if( numeroPregunta==preguntas.size()){
        if(puntaje<8)
        {villano="El Guasón";}
        
        if(puntaje>8 & puntaje<15)  
       {villano="Freddy";}
       
        if(puntaje>=15)
       {villano="Chucky";}
        System.out.println(villano);
       
               
    }
             

  }

}